### ISSUE TITLE
Support .net standard

### ISSUE THREAD

**Issue by PulsarFX** [dotnetjunkie/controllerless#1]
Hi,
any chance to add support for .NET Standard on this project?

**Comment by dotnetjunkie** [comment]
This project depends on ASP.NET Web API 5.0 or later. Why do you need .NET Standard support for Web API? And if so, which .NET Standard version should be supported?

**Comment by PulsarFX** [comment]
I try to put as much as possible into .netStandard2.0 dlls to host the service with asp.net core 
(does this even make sense? I see that swashbuckle has a complete new repo for its asp.net core implementation)

**Comment by dotnetjunkie** [comment]
This project doesn't have any code for (ASP).NET Core. It's just Web API, so I don't see any reason to create a .NET Standard compatible version of off this.

**Comment by PulsarFX** [comment]
hmmm. maybe then I should ask: how to integrate the controllerless approach from solid services with Swashbuckle.AspNetCore? (or should I ask this in solidServices repo?)

**Comment by dotnetjunkie** [comment]
Now we're talking! That's a great question, to which I, unfortunately, have no answer. In the past, I tried to create an ASP.NET Core implementation of [SOLID Services](https://github.com/dotnetjunkie/solidservices/), side-by-side the already available Web API and WCF services, but I didn't succeed, and haven't had any time to research how to implement this on top of ASP.NET Core.

After having an controllerless ASP.NET Core implementation, generating OpenAPI documentation using Swashbuckle.AspNetCore is the easy part.

**Comment by PulsarFX** [comment]
Oh, never thought that I would hit a point where you have no answer to ;-)
maybe this is of any help?
https://stackify.com/asp-net-core-web-api-guide/

**Comment by dotnetjunkie** [comment]
Thanks for the link, but I am aware how to develop 'standard' ASP.NET Core MVC applications. What I'm not yet aware of, however, is what would be the way to create a controllerless Core application. Middleware will probably be the entry point, but what next? What I tried thus far resulted in overly complex code, which made me believe I was heading the wrong direction.

**Comment by PulsarFX** [comment]
I don't know :-( I was happy to get solid services hosted with owinSelfHost a while ago. The code looks rather similar to the .net core config way. But there is no HttpConfiguration anymore.
It is so simple with the C&Q pattern and not having to care for all the ms-mvc stuff around, which they think is neat and fine...

**Comment by dotnetjunkie** [comment]
Exactly. With these patterns, the web infrastructure becomes just a minimal layer. So small that I don't care much about the used web framework. Whatever can run my code is fine.

Still, it would be nice to get this running under ASP.NET Core.

**Comment by alexbrina** [comment]
Maybe this article can shed some light https://www.paddo.org/controllerless-views-in-asp-net-core/amp/

**Comment by dotnetjunkie** [comment]
Interesting read. `IRouter` might be the interception point I was missing.

**Comment by stevengopmo** [comment]
hey guys, after reading this while researching the same thing, I wrote a middleware that works and is pretty close to the delegating handler.  I don't actually think it's too bad code wise but I'd like the master's review (@dotnetjunkie).

``` c#
public sealed class QueryHandlerMiddleware : IMiddleware
{
    private readonly Func<Type, object> _handlerFactory;
    private readonly Dictionary<string, QueryInfo> _queryTypes;
    
    public QueryHandlerMiddleware(Container container)
    {
        _handlerFactory = container.GetInstance;
        _queryTypes = Bootstrapper.GetQueryTypes().ToDictionary(
            info => info.QueryType.Name.Replace("Query", string.Empty),
            info => info,
            StringComparer.OrdinalIgnoreCase);
    }

    public async Task InvokeAsync(HttpContext context, RequestDelegate next)
    {
        var request = context.Request;

        var queryName = GetQueryName(request);

        if (_queryTypes.ContainsKey(queryName))
        {
            // GET operations get their data through the query string, while POST operations
            // expect a JSON object being put in the body.
            var queryData = request.Method.Equals("get", StringComparison.OrdinalIgnoreCase)
                ? SerializationHelpers.ConvertQueryStringToJson(request.QueryString.Value)
                : request.Body.ReadString();

            var info = _queryTypes[queryName];

            var handlerType = typeof(IHandleQueryAsync<,>)
                .MakeGenericType(info.QueryType, info.ResultType);

            try
            {
                dynamic handler = _handlerFactory.Invoke(handlerType);
                dynamic query = JsonConvert.DeserializeObject(queryData, info.QueryType);

                var result = await handler.HandleAsync(query);
                ActionResult returnResult = result.IsSuccess
                    ? new ObjectResult(result)
                    : new BadRequestObjectResult(result.Error);
                await context.WriteResultAsync(returnResult);
            }
            catch (Exception e)
            {
                await context.WriteResultAsync(
                    (ObjectResult)new BadRequestObjectResult(e.Message));
            }

        }
        else
            await next(context);
        
    }

    private static string GetQueryName(HttpRequest request)
    {
        var requestUri = new Uri(request.GetEncodedUrl());
        var segment = requestUri.Segments.LastOrDefault();

        return segment;
    }
}
```

It probably needs a bit of fine tuning but if Steven can point out some areas where he had problems I'm happy to fix and then make a fork and PR to solid services or elsewhere.  Thoughts?

I'm also going to check out doing it with Routing as suggested above but the nice thing about the middleware is that it should work even if you don't add MVC.  Just straight up ASP.NET Core.  At least that's my theory.

**Comment by dotnetjunkie** [comment]
One thing that caught my eye is how the output of _every_ exception is returned to the client in the `catch` block. This can be cause leaking too much information to an attacker, so this is something you should surely not do in production. The Web API example contains a `CreateErrorResponseOrNull` method that only maps a few white-listed exceptions to HTTP response messages.

I'm very interested in a PR. A few things to note if you create a PR:

- Make sure you follow the project's (implicit) coding conventions. For instance, use `this.` on private fields and don't prefix them with `_`.
- The example project uses non-asynchronous abstractions for `IQueryHandler<Q, R>` and `ICommandHandler<T>`. I prefer using this model, even for ASP.NET Core. This keeps the solution more consise, simpler to follow, and consistent.
- Try to follow the code structure of Web API's `QueryDelegatingHandler` and `CommandDelegatingHandler` as much as possible. For instance, the handlers directly return a 404 not found when an unknown query or command url is supplied, instead of passing it on to the `next` delegate.
- If possible, try to create a project that runs out of the box, just as the Web API and WCF projects do.

Cheers

**Comment by stevengopmo** [comment]
@dotnetjunkie I have some code that is ready for review but it has a few TODO's left before it's ready for merge.  Would you prefer a PR that's ready or can I create one now so you can review and make comments as I go?  

I have 4 TODOs + more testing

**Comment by dotnetjunkie** [comment]
You can create a PR, but be aware that  it might take some time for me to review do to temporal, vacational locationing :)

**Comment by stevengopmo** [comment]
hey Stephen, 

I sent a PR that should address most of the things here but would appreciate a review.  Sorry for the delay but since you were on vacation anyway I thought I had a bit of time :)

https://github.com/dotnetjunkie/solidservices/pull/25

I haven't plugged in swagger yet.

**Comment by dotnetjunkie** [comment]
Thank you for this PR. It might take some time for me to review it, since I'm in the process of finishing the manuscript of [my book](https://manning.com/seemann2).

**Comment by PulsarFX** [comment]
For reference: code is in solidservices repo
