### ISSUE TITLE
CORS Question

### ISSUE THREAD

**Issue by timohayes** [dotnetjunkie/controllerless#2]
I'm using Controllerless along with CQRS like in your SolidServices project.

One question. I am using NSwag to generate command/query clients for TypeScript to use in an Angular web application. Since the web app is coming from a different domain in a browser, it gets flagged as a CORS request and fails the pre-flight check. Typically, I would enable CORS in web api middleware, and then decorate the controller with the EnableCors attribute as described [here](https://docs.microsoft.com/en-us/aspnet/web-api/overview/security/enabling-cross-origin-requests-in-web-api). Since Controllerless doesn't have any controllers, do you know how to accomplish this?

**Comment by dotnetjunkie** [comment]
The documentation states [here](https://docs.microsoft.com/en-us/aspnet/web-api/overview/security/enabling-cross-origin-requests-in-web-api#scope-rules-for-enablecors) that you can set CORS globally in the Web API configuration.

If that doesn't work, if I understand correctly from [this](https://docs.microsoft.com/en-us/aspnet/web-api/overview/security/enabling-cross-origin-requests-in-web-api#how-cors-works), CORS is just a set of HTTP header values, which can be set manually.

Let me know if that works for you. I'd be happy to incorporate a working solution as sample in the SOLIDServices.

**Comment by timohayes** [comment]
Thanks! For some reason yesterday the global option didn't work, but now it is working. Must have been me. For anyone else, I added this to my WebApiConfig's Register method:
`var cors = new EnableCorsAttribute("*", "*", "*");
config.EnableCors(cors);`
For production systems, you wouldn't want to leave the "*" obviously.

**Comment by dotnetjunkie** [comment]
I added a CORS example to the Web API project: https://github.com/dotnetjunkie/solidservices/commit/7ac452f9e2c8553f8ba4b03ecf69b1fba0a24d80.
